### ISSUE TITLE
Upgrading to 0.7.0 causing issues with require

### ISSUE THREAD

**Issue by taijuten** [graphboss/aws-sam-webpack-plugin#50]
I'm not quite sure what has changed, I've had a look through the commit and can't see anything obvious.

Whenever hitting my function after upgrading from 0.6.0 to 0.7.0 I get the following:
```
"Error: Cannot find module '../helpers/tenantHelper'\nRequire stack:\n- /var/task/listTenants.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
```

Am I missing something here? Sorry if an obvious question.

**Comment by buggy** [comment]
@taijuten I've just released 0.9.0. Can you try again?

**Comment by taijuten** [comment]
Hey @buggy, thanks for the response. Unfortunately I'm having the same issue with 0.9.0

I'm not using Typescript, and am using your standard webpack configuration, with the exception of some additional externals
```
externals: [
    'aws-sdk',
    'aws-sdk/clients/dynamodb',
    'aws-sdk/clients/sns',
    'aws-sdk/clients/sqs',
    'aws-sdk/clients/apigatewaymanagementapi'
  ],
```

I'm seeing this with both node module requires, and relative requires.

Is there a way I can create an example case for you?

**Comment by taijuten** [comment]
So I've managed to work around this (I think) by specifying the `sam deploy --template` as `./.aws-sam/build/template.yml`

For some reason, this wasn't required as of 0.6.0, but from 0.7.0 it appears to be :shrug: 

I'll keep testing across my repos, and see if this is consistent.

**Comment by jgomes94** [comment]
Hi, I can confirm this is happening. I tried the sam local start-api and it was erroring in the requires. Once i specify the template path everything was fine.

**Comment by jcalderonzumba** [comment]
The Same happens to me with 0.9.0 for the moment I downgraded to 0.6.0 and all works well. I am using typescript by the way.

**Comment by buggy** [comment]
I've merged a change onto `develop` so that it always generates a `template.yaml`. I think the change between those versions that might have caused this was generating `template.yml` if that's what you called it. The change will ship with 0.10.0
